### ISSUE TITLE
Error: b'refs/heads/master'

### ISSUE THREAD

**Issue by NellieNellou** [cnigfr/Reseaux-eaux#1]
Bonjour,

En cliquant sur "install" pour l'installation de la collection RAEPA Assainissement, j'ai eu le message d'erreur suivant : 
![Sans titre](https://github.com/cnigfr/Reseaux-eaux/assets/161009700/cfb45d70-fac4-461d-964d-66e30644c25d)

(Pour le RAEPA eau potable pas de soucis la collection s'est installée correctement)

**Comment by AlainPasquier** [comment]
Je ne comprends pas pourquoi sur le même dépôt un répertoire fonctionne et pas l'autre. Désolè.

**Comment by AlainPasquier** [comment]
N'arrivant pas à réparer le github de manière sécurisée, un dépot gitlab miroir a été créé et le tutoriel d'utilisation de resource sharing modifié.  ---> https://gitlab.com/star-eau/symbologie
