### ISSUE TITLE
Mauvais lien d'accès au cryptpad

### ISSUE THREAD

**Issue by flacombe** [cnigfr/Reseaux-eaux#4]
Bonjour

Il semble qu'il y ait une erreur à l'ouverture du lien cryptpad pour participer à l'appel à commentaire.
Au clic du lien, j'obtiens le message suivant :
![image](https://github.com/cnigfr/Reseaux-eaux/assets/5690599/72175c12-5b3b-45fd-a7f8-ca07525d5b31)

Ce n'est pas le cas partout. J'ai retrouvé ces mauvais liens sur les pages suivantes au moins :
- https://github.com/cnigfr/Reseaux-eaux/releases/tag/AC_juin_2024
- https://www.astee.org/publications/geostandard-de-reseaux-star-eau/

Pourriez-vous corriger s'il vous plaît ?

**Comment by pabonin** [comment]
En effet je n'ai pas réussi à accéder au cryptpad. 
Pouvez-vous nous indiquer le bon lien pour diffusion de l'appel à commentaire ?

Merci

**Comment by flacombe** [comment]
Le bon lien est le suivant : https://cryptpad.fr/sheet/#/2/sheet/edit/wfNUCXes-vLBmd1O1kalH-T2/embed/

**Comment by AlainPasquier** [comment]
Merci pour le signalement, les liens cités sont tous corrects, mais il s'agit d'une fonction de protection de cryptpad. J'ai modifié la sécurité et cela devrait fonctionné. Je clos le ticket et surveille le fonctionnement.
